- e2e/images/mysql/Dockerfile
- e2e/images/mysql/cmd/main.go
- e2e/images/mysql/go.mod
- e2e/images/mysql/go.sum
Adding container image code for the MySQL e2e
> Adding container for mysql e2e

- README.md
Signed-off-by: Ahmed ElSayed <ahmels@microsoft.com>
> Add master build badge to README

- e2e/images/redis/lists/Dockerfile
- e2e/images/redis/lists/app.js
- e2e/images/redis/lists/package-lock.json
- e2e/images/redis/lists/package.json
In preparation for adding e2e tests around the Redis Lists Scaler
> Adding code for testing Redis Lists Scaler

- .github/workflows/master.yml
- e2e/images/build.sh
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
Closes #8
> feat: Build & push to GitHub Container Registry

- .github/workflows/master.yml
- README.md
Signed-off-by: Tom Kerkhove kerkhove.tom@gmail.com
> fix: Add missing ghcr.io URL to login to

- e2e/images/postgresql/Dockerfile
- e2e/images/postgresql/cmd/main.go
- e2e/images/postgresql/go.mod
- e2e/images/postgresql/go.sum
Signed-off-by: jorturfer <jorge_turrado@hotmail.es>
I'm creating e2e test for PostgreSQL scaler. This PR adds an e2e test image for it, following the same approach that is used in mysql
> Adds PostgreSQL image for e2e test

- .github/CODEOWNERS
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>
I'd like to be notified on PRs here
> Add @jorturfer as code owner

- e2e/images/metrics-api/Dockerfile
- e2e/images/metrics-api/README.md
- e2e/images/metrics-api/go.mod
- e2e/images/metrics-api/go.sum
- e2e/images/metrics-api/server.go
Signed-off-by: Alejandro Dominguez <adborroto90@gmail.com>
A simple Docker container written in **go** that will expose a value metric. To be use for a Keda scaler [Metrics APi](https://keda.sh/docs/2.3/scalers/metrics-api/) e2e test.
> Adding metric-api image for e2e test

- e2e/images/mysql/cmd/main.go
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>
> Fix mysql container restarts changing the isolation level

- e2e/images/selenium-grid/wdio.conf.js
Signed-off-by: Brandon Wolfe <Wolfe1@gmail.com>
For use in https://github.com/kedacore/keda/pull/3062
> Add edge to config

- e2e/integrations/azure-pipelines/pipeline.yml
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>
I need this change for az pipelines e2e tests with activation
> chore: update pipeline

- e2e/images/prometheus/Dockerfile
- e2e/images/prometheus/README.md
- e2e/images/prometheus/go.mod
- e2e/images/prometheus/go.sum
- e2e/images/prometheus/main.go
Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>
> prometheus: update test app & image

- e2e/images/mysql/Dockerfile
- e2e/images/mysql/go.mod
Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>
Fixes #
> bump golang version for mysql image

- e2e/integrations/github/readme.MD
This PR should be merged once these vars are updated https://github.com/kedacore/keda/pull/4281#issuecomment-1460537351
> chore: update envs

- e2e/images/rabbitmq/cmd/receive/receive.go
> chore: support queue argument for rabbitmq receiver

- e2e/images/azure-pipelines/advagent/Dockerfile
- e2e/images/azure-pipelines/advagent/readme.MD
- e2e/images/azure-pipelines/advagent/start.sh
- e2e/integrations/azure-pipelines/demand-pipeline.yml
Advanced agent for ADO pipelines to support jobs, not objects
Fixes #
(#kedacore/4387)
> Test Extensions for (#4387)

- e2e/images/metrics-api/server.go
> chore: add a log in metrics api

- e2e/images/nats-jetstream/Dockerfile
- e2e/images/nats-jetstream/cmd/main.go
- e2e/images/nats-jetstream/go.mod
- e2e/images/nats-jetstream/go.sum
> feat: add nats-jetstream image

- .github/workflows/test-runner-gha-job.yaml
- e2e/integrations/github/readme-gha.MD
Added setup for GHA runner test
Fixes #
https://github.com/kedacore/keda/issues/4651
> New GHA e2e test functionality

- .github/workflows/keda-k6-runner.yaml
- .github/workflows/pr.yml
- Makefile
- k6-runner/Dockerfile
> add k6 runner image

- README.md
Relates to kedacore/governance#63
> chore: KEDA is a CNCF Graduated project

- e2e/images/apache-ab/Dockerfile
> feat: add Apache AB image

- e2e/images/cloudevents-http/README.md
- e2e/images/cloudevents-http/example.json
- e2e/images/cloudevents-http/server.go
> chore(cloudevents-e2e): Return multiple events and add examples

- e2e/images/hey/Dockerfile
> Use userId for hey image

- e2e/integrations/azure-pipelines/pipeline-aad-wi.yml
> Add new az-pipeline

- e2e/images/azure-eventhub-dotnet/EventHubWorker.csproj
This image is required to validate [this issue](https://github.com/kedacore/keda/issues/5574) once it's solved, don't merge it until the PR is ready or we will break e2e tests
Related https://github.com/kedacore/keda/issues/5574
> chore: bump event hub dep

- tools/Dockerfile
Sorry it took so long for me to get to this
Fixes #136
> Get latest operator-sdk instead of old v1.0.1

- e2e/images/artemis/producer/src/main/java/org/bal/starter/App.java
- e2e/images/artemis/producer/src/main/resources/application.yml
> feat: Add dynamic amount of messages for Artemis producer

- e2e/images/nsq/main.go
This adds the ability to control how long the consumer takes to process messages for the NSQ e2e tests in kedacore/keda#6230.
> fix: adds sleep flag to nsq e2e test image

- e2e/images/nats-jetstream/Dockerfile
- e2e/images/nats-jetstream/go.mod
> fix image generation

- tools/Dockerfile
> chore: Add some deps to the base image

- e2e/images/external-scaler/Dockerfile
- e2e/images/external-scaler/go.mod
> fix external scaler image issue

- e2e/images/azure-eventhub-golang/Dockerfile
> Bump go version

- tools/Dockerfile
> chore: Use git from ubuntu repository

- e2e/images/external-scaler/main.go
> chore: Add ready check to external-scaler image

- e2e/images/external-scaler/main.go
> Restore original port for external-scaler

- e2e/images/external-scaler/main.go
> chore: Add keep alive config for gRPC server

- e2e/images/external-scaler/main.go
> chore: Implement StreamIsActive for external scaler

- e2e/images/external-scaler/main.go
> chore: Remove keep alive

- e2e/images/websockets/Dockerfile
- e2e/images/websockets/README.md
- e2e/images/websockets/client.js
- e2e/images/websockets/package.json
- e2e/images/websockets/server.js
websocket e2e server for https://github.com/kedacore/http-add-on/pull/835
- [x ] Commits are signed with Developer Certificate of Origin (DCO)
Fixes #
> websocket e2e server for https://github.com/kedacore/http-add-on/pull/835
